### ISSUE TITLE
Relicensing vom LGPL3+ to MPL2?

### ISSUE THREAD

**Issue by bertwesarg** [ComputationalRadiationPhysics/llama#18]
See ComputationalRadiationPhysics/alpaka#637. Does the same arguments hold here too?

**Comment by theZiz** [comment]
I doubt. This is only needed for the **examples**. The llama examples are already public domain asfair.

**Comment by bertwesarg** [comment]
But what about the argument, that the LGPL is not well defined for header only libraries?

**Comment by theZiz** [comment]
This argument is invalid for LGPL**v3**.

**Comment by theZiz** [comment]
Btw, here you can see my example license:
https://github.com/ComputationalRadiationPhysics/llama/blob/develop/examples/simpletest/simpletest.cpp
Right now only in develop, not master.

**Comment by theZiz** [comment]
See also: http://eigen.tuxfamily.org/index.php?title=Licensing_FAQ&oldid=1117#But_doesn.27t_the_LGPL_have_issues_with_code_that_is_in_header_files.2C_and_template_libraries.3F

**Comment by ax3l** [comment]
Our plan is to re-license the core of our header-only libraries for simplicity from LGPL to MPL-2.0 step by step. Next will be cupla.
As Alex said, LGPLv3 is ok for header-only libs, [see sec. 3](https://www.gnu.org/licenses/lgpl-3.0.de.html), but since this is the only section of the whole LGPLv3 that we care about we want a clear and simple license.
([The original issue in alpaka](https://github.com/ComputationalRadiationPhysics/alpaka/issues/637) contains some more links to materials and the same considerations from Eigen in the past.)

**Comment by bertwesarg** [comment]
Thanks, feel free to close this than.
